name: build manylinux

on: [push, pull_request]

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
          - 3.5
          - 3.6
          - 3.7
          - 3.8
    container: 
      image: quay.io/pypa/manylinux1_x86_64:2020-03-07-9c5ba95
      env:
        PATH: /root/.local/bin:/opt/python/cp36-cp36m/bin:/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/python/cp35-cp35m/bin:/opt/python/cp36-cp36m/bin:/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38/bin
      options: --user root
    env:
      HOME: /root
      PYTHON: python${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        $PYTHON -m pip install --upgrade pip
        $PYTHON -m pip install -r requirements.txt
        $PYTHON -m pip install -e .

    - name: run test
      run: pytest

    - name: Build
      run: |
        $PYTHON setup.py bdist_wheel
        $PYTHON -m auditwheel repair dist/*whl

    - name: Publish pypi
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
      run: |
        twine upload wheelhouse/*whl -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASS }}

  build_aarch64:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    name: "build (${{ matrix.pyver }}, aarch64)"
    strategy:
      matrix:
        pyver: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      py: /opt/python/${{ matrix.pyver }}/bin/python
      img: quay.io/pypa/manylinux2014_aarch64
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1

    - name: Install dependencies
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
          source .env/bin/activate && \
          python -m pip install --upgrade pip && \
          python -m pip install -r requirements.txt && \
          python -m pip install -e . && \
          deactivate'

    - name: Run test
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '\
          source .env/bin/activate && \
          python -m pytest && \
          deactivate'

    - name: Build
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} \
          bash -exc '\
          source .env/bin/activate && \
          pip install wheel && \
          python setup.py bdist_wheel && \
          python -m auditwheel repair dist/*whl && \
          deactivate'

    - name: Publish pypi
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
      run: |
        twine upload wheelhouse/*whl -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASS }}
